# Generated by Django 4.0.5 on 2023-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feedbacks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Behance URL'),
        ),
    ]
